apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timescaledb-single-chart
  namespace: {{ .Release.Namespace }}
  labels:
    app: timescaledb-single-chart
    chart: timescaledb-single-0.5.5
    release: timescaledb-single-chart
    heritage: Tiller
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
subjects:
  - kind: ServiceAccount
    name: harness-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: timescaledb-single-chart
