apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timescaledb-single-chart
  namespace: {{ .Release.Namespace }}
  labels:
    app: timescaledb-single-chart
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations: {}
subjects:
  - kind: ServiceAccount
    name: harness-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: timescaledb-single-chart
